const actionType = {
  GET_RANDOM_USER: 'GET_RANDOM_USER',
  GET_RANDOM_USER_SUCCESS: 'GET_RANDOM_USER_SUCCESS',
  GET_RANDOM_USER_FAILED: 'GET_RANDOM_USER_FAILED',
  ADD_MY_FAVOURITE: 'ADD_MY_FAVOURITE'
}

export default actionType